const countryToFlag: Record<string, string> = {
  "United States": "🇺🇸",
  "Canada": "🇨🇦",
  "Mexico": "🇲🇽",
  "United Kingdom": "🇬🇧",
  "Germany": "🇩🇪",
  "France": "🇫🇷",
  "Italy": "🇮🇹",
  "Spain": "🇪🇸",
  "Netherlands": "🇳🇱",
  "Belgium": "🇧🇪",
  "Switzerland": "🇨🇭",
  "United Arab Emirates": "🇦🇪",
  "Saudi Arabia": "🇸🇦",
  "Qatar": "🇶🇦",
  "Kuwait": "🇰🇼",
  "Bahrain": "🇧🇭",
  "China": "🇨🇳",
  "Japan": "🇯🇵",
  "India": "🇮🇳",
  "Singapore": "🇸🇬",
  "Australia": "🇦🇺",
  "Brazil": "🇧🇷",
  "Argentina": "🇦🇷",
  "Chile": "🇨🇱",
  "Colombia": "🇨🇴",
  "Peru": "🇵🇪",
  "Russia": "🇷🇺",
  "South Africa": "🇿🇦",
  "Nigeria": "🇳🇬",
  "Kenya": "🇰🇪",
  "Egypt": "🇪🇬",
  "Morocco": "🇲🇦",
  "Turkey": "🇹🇷",
  "Israel": "🇮🇱",
  "South Korea": "🇰🇷",
  "Thailand": "🇹🇭",
  "Malaysia": "🇲🇾",
  "Indonesia": "🇮🇩",
  "Philippines": "🇵🇭",
  "Vietnam": "🇻🇳",
  "New Zealand": "🇳🇿",
  "Sweden": "🇸🇪",
  "Norway": "🇳🇴",
  "Denmark": "🇩🇰",
  "Finland": "🇫🇮",
  "Austria": "🇦🇹",
  "Portugal": "🇵🇹",
  "Ireland": "🇮🇪",
  "Luxembourg": "🇱🇺",
  "Poland": "🇵🇱",
  "Czech Republic": "🇨🇿",
  "Hungary": "🇭🇺",
  "Romania": "🇷🇴",
  "Bulgaria": "🇧🇬",
  "Croatia": "🇭🇷",
  "Slovenia": "🇸🇮",
  "Slovakia": "🇸🇰",
  "Estonia": "🇪🇪",
  "Latvia": "🇱🇻",
  "Lithuania": "🇱🇹",
  "Greece": "🇬🇷",
  "Cyprus": "🇨🇾",
  "Malta": "🇲🇹"
};

export const getCountryFlag = (countryName: string | null | undefined): string => {
  if (!countryName) return "🌍";
  return countryToFlag[countryName] || "🌍";
};